---
name: Install python 3.10.10

on:
  pull_request:

jobs:

  install-python:
    name: Install Python
    runs-on: ubuntu-latest

    steps:
    - name: Check out Repo Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10

    - name: Display Python version
      run: python --version

    - name: Install Dependencies
      run: python -m pip install -r requirements.txt

    - name: Display Installed Dependencies
      run: python -m pip freeze

    - name: Run Tests
      run: python -m pytest
